# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6e089f02e8797be6068c7f202275291b2722589be84476338958c699c710353868c4e6eff15bba515926bf2ec24df4f7107413acd519505d1bf7e12d8c522fd

test:
  secret_key_base: 898b50ba65baf5c4335f2f74079c54d3d260eec6a0b685597564913999fa2bd7ffc387238c1dd345348395cfbffad9e116e7ec1b7f0ca66aa30cb8de28c035fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
